## numpy array and basic
learn bout numpy


In [2]:
import numpy as np

In [ ]:
arr_1d=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("1d array: ",arr_1d)


arr_2d=np.array([[1, 2, 3, 4, 5] , [6, 7, 8, 9, 10]])
print("2d arrray; ",arr_2d)


### list vs numpy array

In [ ]:
py_list=[1, 2, 3, 4, 5]
print("python list multiplication: ", py_list*2)
np_array=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("array multiplication in numpy: ", py_array*2)

import time
start_time = time.time()
py_list=[i*2 for i in range(1000000)]
print("\nTime taken to multiply list: ", time.time() - start_time)

start_time = time.time()
np_array=np.arange(1000000)*2
print("\nTime taken to multiply array: ", time.time() - start_time)

### creating array from scracth


In [3]:
zeros = np.zeros((3, 4))
print("zeros array\n",zeros)

ones = np.ones((3,4))
print("ones array:\n",ones)
full = np.full((3,4),8)
print("full array any nummber:\n", full)

random = np.random.random((2,3))
print("random array:\n", random)

sequence = np.arange(0, 20, 2)
print("sequence array:\n", sequence)

eye = np.eye(2,4, k=1)
print("eye array:\n", eye)


zeros array
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
full array any nummber:
 [[8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]]
random array:
 [[0.10489488 0.18319617 0.22488217]
 [0.97175825 0.09255727 0.34523934]]
sequence array:
 [ 0  2  4  6  8 10 12 14 16 18]
eye array:
 [[0. 1. 0. 0.]
 [0. 0. 1. 0.]]


### vector , matrices, tensor


In [ ]:
vector_a = np.array([1,2,3])
print("vector a: ", vector_a)

matrix_a = np.array ([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
print("matrix a:\n", matrix_a)

tensor_a = np.array([[[1,2],[9,10]],
                      [[3,4],[11,12]],
                      [[5,6],[13,14]],
                      [[7,8],[15,16]]])
print("tensor a:\n", tensor_a)

### array properties

In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print("shape of array: ", arr.shape)
print("dimensions of array: ", arr.ndim)
print("size of array:", arr.size)
print("data type of array: ", arr.dtype)
print("item size of array: ", arr.itemsize)
print("total bytes consumed by array: ", arr.nbytes)

shape of array:  (3, 3)
dimensions of array:  2
size of array: 9
data type of array:  int64
item size of array:  8
total bytes consumed by array:  72


## array reshaping

In [41]:
arr = np.arange(12)
print("original array: ", arr)

reshaped_arr = arr.reshape((3, 4))
print("reshaped array:\n", reshaped_arr)

flattened_arr = reshaped_arr.flatten()
print("flattened array: ", flattened_arr)

# ravel() returns a flattened array, but it is a view of the original array, meaning that changes to the raveled array will affect the original array. On the other hand, flatten() returns a copy of the original array, so changes to the flattened array will not affect the original array.
reveled_arr = reshaped_arr.ravel()
print("reveled array: ", reveled_arr)

transposed_arr = reshaped_arr.T
print("transposed array:\n", transposed_arr)

original array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshaped array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
flattened array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
reveled array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
transposed array:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
