## numpy array operations


In [2]:
import numpy as np

In [11]:
arr= np.arange(1,12)
print("original array: ", arr)
print("basic slicing: ", arr[2:7])
print("slicing with step: ", arr[2:7:2])
print("slicing with negative step: ", arr[7:2:-1])

original array:  [ 1  2  3  4  5  6  7  8  9 10 11]
basic slicing:  [3 4 5 6 7]
slicing with step:  [3 5 7]
slicing with negative step:  [8 7 6 5 4]


In [ ]:
arr_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])
print("specific element:", arr_2d[1, 2])
print("entire row:", arr_2d[1])
print("entire column: ", arr_2d[:, 2])

specific element: 6


## sorting

In [16]:
unsorted_arr = np.array([5, 2, 9, 1, 5, 6])
sorted_arr = np.sort(unsorted_arr)
print("unsorted array: ", unsorted_arr)
print("sorted array: ", sorted_arr)

arr_2d_unsorted = np.array([[31, 28, 1],
                             [6, 15, 4],
                             [89, 18, 71]])
print("sorted by columns: ", np.sort(arr_2d_unsorted, axis=0))
print("sorted by rows: ", np.sort(arr_2d_unsorted, axis=1))
print("sorted flattened array: ", np.sort(arr_2d_unsorted, axis=None))


unsorted array:  [5 2 9 1 5 6]
sorted array:  [1 2 5 5 6 9]
sorted by columns:  [[ 6 15  1]
 [31 18  4]
 [89 28 71]]
sorted by rows:  [[ 1 28 31]
 [ 4  6 15]
 [18 71 89]]
sorted flattened array:  [ 1  4  6 15 18 28 31 71 89]


## filtering

In [4]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
even_numbers = numbers[numbers % 2 == 0]
print("even:", even_numbers)

even: [ 2  4  6  8 10]


## filter with mask

In [18]:
mask = (numbers > 3)
print (" numbers greater than 3: ", numbers[mask])

 numbers greater than 3:  [ 4  5  6  7  8  9 10]


## fancy indexing versus np.where()

In [5]:
indices = [0, 2, 4]
print (numbers [indices])
where_result = np.where (numbers > 5)
print ("NP where", numbers [where_result[0]])
print ("NP where", numbers [where_result])

[1 3 5]
NP where [ 6  7  8  9 10]
NP where [ 6  7  8  9 10]


In [7]:
condition_array = np.where(numbers > 5, numbers*4, numbers)
print (condition_array)

[ 1  2  3  4  5 24 28 32 36 40]



## adding and removing of data

In [9]:
arr_1 = np.array([1, 2, 3])
arr_2 = np.array([4, 5, 6])

combined_arr = np.concatenate((arr_1, arr_2))
print("combined array: ", combined_arr)

combined array:  [1 2 3 4 5 6]


### array compatibility

In [ ]:
a=np.array([1, 2, 3])
b=np.array([4, 5, 6])
c=np.array([7, 8, 9])

print("compatibiblity shape", a.shape== b.shape and b.shape == c.shape)

compatibiblity shape True


In [18]:
original = np.array([[1, 2], [3, 4]])
add_new_row = np.array([5, 6])

updated_row= np.vstack((original, add_new_row))
print("updated array: ", updated_row)

add_new_column = np.array([[7], [8], [9]])
updated_column = np.hstack((updated_row, add_new_column))
print("updated array with new column: ", updated_column)

updated array:  [[1 2]
 [3 4]
 [5 6]]
updated array with new column:  [[1 2 7]
 [3 4 8]
 [5 6 9]]


In [19]:
arr=np.array([1, 2, 3, 4, 5])
deleted_element = np.delete(arr, 2)
print("array after deletion: ", deleted_element)


array after deletion:  [1 2 4 5]
