## advance operation with bussiness example


In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [4]:
sales_data = np.array([
                        [1, 150000, 180000, 220000, 250000], # Paradise Biryani
                        [2, 120000, 140000, 160000, 190000], # Beijing Bites
                        [3, 200000, 230000, 260000, 300000], # Pizza Hub
                        [4, 180000, 210000, 240000, 270000], # Burger Point
                        [5, 160000, 185000, 205000, 230000] # Chai Point 
                    ])

print("===zomato sales analysis data===")
print("\nsales shape:", sales_data.shape)
print("data of first 3 resturants:\n",sales_data[:3])


===zomato sales analysis data===

sales shape: (5, 5)
data of first 3 resturants:
 [[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]]
